name: "Build"
on:
  - "push"
jobs:
  build:
    name: "Build on JDK ${{ matrix.jdk }}"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        jdk:
          - 11
    steps:
      - uses: actions/checkout@v2
      - name: "Set up JDK ${{ matrix.jdk }}"
        uses: actions/setup-java@v2
        with:
          java-version: "${{ matrix.jdk }}"
          distribution: "zulu"
      - name: "Build with Gradle"
        run: ./gradlew check distTar
      - name: "Upload Artifact"
        uses: actions/upload-artifact@v2
        with:
          name: "Kotlin Application"
          path: "build/distributions/repo.tar"
          retention-days: 1
  build-and-push-image:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: "Checkout"
        uses: actions/checkout@v2
      - uses: actions/download-artifact@v2
        with:
          name: "Kotlin Application"
          path: "build/distributions/"
      - name: "Untar files"
        run: mkdir -p build/install && tar -xvf build/distributions/repo.tar -C $_
      - name: "Set up Docker Buildx"
        uses: docker/setup-buildx-action@v1
      - name: "Login to GHCR"
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password:  ${{ secrets.GITHUB_TOKEN }}
      - name: "Build and push"
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: |
            ghcr.io/heapy/repo.kotlin.link:main
            ghcr.io/heapy/repo.kotlin.link:b${{ github.run_number }}
